"""Constants for the Directional RF Fan integration."""

from __future__ import annotations

DOMAIN = "directional_rf_fan"
PLATFORMS = ["fan", "button", "sensor"]
STATIC_URL_PATH = f"/{DOMAIN}_static"
LEARN_IMAGE_URL = f"{STATIC_URL_PATH}/learn_power_cycle.svg"

CONF_TRANSMITTER = "transmitter"
CONF_REPEATS = "repeats"
CONF_CODE_ON = "code_on"
CONF_CODE_OFF = "code_off"
CONF_CODE_IN_PLUS = "code_in_plus"
CONF_CODE_IN_MINUS = "code_in_minus"
CONF_CODE_OUT_PLUS = "code_out_plus"
CONF_CODE_OUT_MINUS = "code_out_minus"
CONF_FAN_SLOT = "fan_slot"
CONF_CODE_SET_SOURCE = "code_set_source"
CONF_COMMAND_PROFILE = "command_profile"
CONF_REMOTE_ADDRESS = "remote_address"
CONF_RF_PROTOCOL = "rf_protocol"
CONF_FREQUENCY = "frequency"

CODE_SET_SOURCE_SLOT = "slot"
CODE_SET_SOURCE_MANUAL = "manual"
FAN_SLOT_MANUAL = "manual"

COMMAND_PROFILE_A = "profile_a"

RF_PROTOCOL_RC_SWITCH_1 = "rc_switch_1"

PRESET_IN = "In"
PRESET_OUT = "Out"
PRESET_MODES = [PRESET_IN, PRESET_OUT]

COMMAND_ON = "on"
COMMAND_OFF = "off"
COMMAND_IN_PLUS = "in_plus"
COMMAND_IN_MINUS = "in_minus"
COMMAND_OUT_PLUS = "out_plus"
COMMAND_OUT_MINUS = "out_minus"

COMMAND_TO_CONF = {
    COMMAND_ON: CONF_CODE_ON,
    COMMAND_OFF: CONF_CODE_OFF,
    COMMAND_IN_PLUS: CONF_CODE_IN_PLUS,
    COMMAND_IN_MINUS: CONF_CODE_IN_MINUS,
    COMMAND_OUT_PLUS: CONF_CODE_OUT_PLUS,
    COMMAND_OUT_MINUS: CONF_CODE_OUT_MINUS,
}

DEFAULT_REPEATS = 10
DEFAULT_FREQUENCY = 433_920_000
DEFAULT_TIMEBASE_US = 350
LEARN_DURATION_SECONDS = 6
COMMAND_SETTLE_TIME = 0.2
SPEED_COUNT = 6
RECALIBRATE_STEPS = SPEED_COUNT

DEFAULT_CODES = {
    CONF_CODE_ON: "55BE0AF5",
    CONF_CODE_OFF: "55BE0DF2",
    CONF_CODE_OUT_PLUS: "55BE0BF4",
    CONF_CODE_OUT_MINUS: "55BE0CF3",
    CONF_CODE_IN_PLUS: "55BE0EF1",
    CONF_CODE_IN_MINUS: "55BE0FF0",
}

COMMAND_PROFILE_COMMANDS = {
    COMMAND_PROFILE_A: {
        COMMAND_ON: 0x0A,
        COMMAND_OUT_PLUS: 0x0B,
        COMMAND_OUT_MINUS: 0x0C,
        COMMAND_OFF: 0x0D,
        COMMAND_IN_PLUS: 0x0E,
        COMMAND_IN_MINUS: 0x0F,
    },
}

FAN_SLOT_OPTIONS = ["1", "2", FAN_SLOT_MANUAL]

FAN_SLOT_REMOTE_ADDRESSES = {
    "1": 0x55BE,
    "2": 0x6234,
}
