"""Constants for the Directional RF Fan integration."""

from __future__ import annotations

DOMAIN = "directional_rf_fan"
PLATFORMS = ["fan", "button"]
STATIC_URL_PATH = f"/{DOMAIN}_static"
LEARN_IMAGE_URL = f"{STATIC_URL_PATH}/learn_power_cycle.svg"

CONF_TRANSMITTER = "transmitter"
CONF_REPEATS = "repeats"
CONF_CODE_ON = "code_on"
CONF_CODE_OFF = "code_off"
CONF_CODE_IN_PLUS = "code_in_plus"
CONF_CODE_IN_MINUS = "code_in_minus"
CONF_CODE_OUT_PLUS = "code_out_plus"
CONF_CODE_OUT_MINUS = "code_out_minus"
CONF_FAN_SLOT = "fan_slot"
CONF_CODE_SET_SOURCE = "code_set_source"
CONF_COMMAND_PROFILE = "command_profile"
CONF_REMOTE_ADDRESS = "remote_address"
CONF_RF_PROTOCOL = "rf_protocol"
CONF_FREQUENCY = "frequency"

CODE_SET_SOURCE_SLOT = "slot"
CODE_SET_SOURCE_MANUAL = "manual"
FAN_SLOT_MANUAL = "manual"

COMMAND_PROFILE_A = "profile_a"
COMMAND_PROFILE_B = "profile_b"

RF_PROTOCOL_RC_SWITCH_1 = "rc_switch_1"
RF_PROTOCOL_OOK_PWM_420_1220 = "ook_pwm_420_1220"

PRESET_IN = "In"
PRESET_OUT = "Out"
PRESET_MODES = [PRESET_IN, PRESET_OUT]

COMMAND_ON = "on"
COMMAND_OFF = "off"
COMMAND_IN_PLUS = "in_plus"
COMMAND_IN_MINUS = "in_minus"
COMMAND_OUT_PLUS = "out_plus"
COMMAND_OUT_MINUS = "out_minus"

COMMAND_TO_CONF = {
    COMMAND_ON: CONF_CODE_ON,
    COMMAND_OFF: CONF_CODE_OFF,
    COMMAND_IN_PLUS: CONF_CODE_IN_PLUS,
    COMMAND_IN_MINUS: CONF_CODE_IN_MINUS,
    COMMAND_OUT_PLUS: CONF_CODE_OUT_PLUS,
    COMMAND_OUT_MINUS: CONF_CODE_OUT_MINUS,
}

DEFAULT_REPEATS = 10
DEFAULT_FREQUENCY = 433_920_000
PROFILE_B_FREQUENCY = DEFAULT_FREQUENCY
DEFAULT_TIMEBASE_US = 350
PWM_SHORT_US = 420
PWM_LONG_US = 1220
PWM_SYNC_HIGH_US = 800
PWM_RESET_US = 11916
LEARN_DURATION_SECONDS = 6
COMMAND_SETTLE_TIME = 0.2
SPEED_COUNT = 6
RECALIBRATE_STEPS = SPEED_COUNT

DEFAULT_CODES = {
    CONF_CODE_ON: "55BE0AF5",
    CONF_CODE_OFF: "55BE0DF2",
    CONF_CODE_OUT_PLUS: "55BE0BF4",
    CONF_CODE_OUT_MINUS: "55BE0CF3",
    CONF_CODE_IN_PLUS: "55BE0EF1",
    CONF_CODE_IN_MINUS: "55BE0FF0",
}

COMMAND_PROFILE_COMMANDS = {
    COMMAND_PROFILE_A: {
        COMMAND_ON: 0x0A,
        COMMAND_OUT_PLUS: 0x0B,
        COMMAND_OUT_MINUS: 0x0C,
        COMMAND_OFF: 0x0D,
        COMMAND_IN_PLUS: 0x0E,
        COMMAND_IN_MINUS: 0x0F,
    },
    COMMAND_PROFILE_B: {
        COMMAND_IN_MINUS: 0xE0,
        COMMAND_IN_PLUS: 0xE2,
        COMMAND_OFF: 0xE4,
        COMMAND_OUT_MINUS: 0xE6,
        COMMAND_OUT_PLUS: 0xE8,
        COMMAND_ON: 0xEA,
    },
}

COMMAND_PROFILE_PROTOCOLS = {
    COMMAND_PROFILE_A: RF_PROTOCOL_RC_SWITCH_1,
    COMMAND_PROFILE_B: RF_PROTOCOL_OOK_PWM_420_1220,
}

COMMAND_PROFILE_FREQUENCIES = {
    COMMAND_PROFILE_A: DEFAULT_FREQUENCY,
    COMMAND_PROFILE_B: PROFILE_B_FREQUENCY,
}

FAN_SLOT_OPTIONS = [str(slot) for slot in range(1, 11)] + [FAN_SLOT_MANUAL]

FAN_SLOT_REMOTE_ADDRESSES = {
    "1": 0x55BE,
    "2": 0x6234,
    "3": 0xA13C,
    "4": 0xC742,
    "5": 0x6D91,
    "6": 0xE35A,
    "7": 0x19F6,
    "8": 0x8B24,
    "9": 0xD0E7,
    "10": 0x4C8A,
}

FAN_SLOT_PROFILES = {
    "1": [COMMAND_PROFILE_A],
    "2": [COMMAND_PROFILE_A],
    "3": [COMMAND_PROFILE_A, COMMAND_PROFILE_B],
    "4": [COMMAND_PROFILE_A, COMMAND_PROFILE_B],
    "5": [COMMAND_PROFILE_A, COMMAND_PROFILE_B],
    "6": [COMMAND_PROFILE_A, COMMAND_PROFILE_B],
    "7": [COMMAND_PROFILE_A, COMMAND_PROFILE_B],
    "8": [COMMAND_PROFILE_A, COMMAND_PROFILE_B],
    "9": [COMMAND_PROFILE_A, COMMAND_PROFILE_B],
    "10": [COMMAND_PROFILE_A, COMMAND_PROFILE_B],
}
